version: '3.8'

services:
  database:
    image: mysql:8.0.27
    container_name: ${APP_NAME}_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${SQL_DB}
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_USER= ${SQL_USER}
    volumes:
      - spending-control-data:/var/lib/mysql
    networks:
      - spending-control-network
    ports:
      - 33306:3306

  nginx:
    build: ./nginx
    container_name: ${APP_NAME}_server
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./src:${WORDK_DIR}
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/app.conf:/etc/nginx/sites-available/application.conf
      - ./nginx/app.conf:/etc/nginx/sites-enabled/application
      - ./nginx/log:/var/log/nginx
    networks:
      - spending-control-network
    depends_on:
      - database
      - app

  app:
    container_name: app
    build:
      args:
        user: ${USER_MACHINE}
        uid: ${UID_MACHINE}
        workdir: ${WORDK_DIR}
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:${WORDK_DIR}
    networks:
      - spending-control-network
    depends_on:
      - database

networks:
  spending-control-network:
    driver: bridge

volumes:
  spending-control-data:
